// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TableTopCharacterManager.Models;

namespace TableTopCharacterManager.Migrations
{
    [DbContext(typeof(TableTopCharacterManagerContext))]
    [Migration("20171017151439_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TableTopCharacterManager.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("CharacterClass")
                        .IsRequired();

                    b.Property<string>("CharacterName")
                        .IsRequired();

                    b.Property<string>("CharacterRace")
                        .IsRequired();

                    b.Property<string>("Equipment");

                    b.Property<int>("Gold");

                    b.Property<bool>("IsAlive");

                    b.Property<int>("Level");

                    b.Property<string>("PhysicalDescription");

                    b.HasKey("Id");

                    b.ToTable("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
